#!/usr/bin/env ruby
#^syntax detection

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-stdlib'
mod 'puppetlabs-vcsrepo'

mod 'puppetfinland-os',
    :git => 'https://github.com/Puppet-Finland/os.git'

mod 'puppetfinland-packetfilter',
    :git => 'https://github.com/Puppet-Finland/packetfilter.git'

mod 'puppetfinland-tomcat',
    :git => 'https://github.com/Puppet-Finland/puppet-module-tomcat.git',
    :tag => '1.1.0'

