#!/usr/bin/env ruby
#^syntax detection

forge 'https://forgeapi.puppetlabs.com'

mod 'stahnma-epel'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-vcsrepo'

mod 'puppetfinland-dirsrv',
    :git => 'https://github.com/Puppet-Finland/puppet-dirsrv.git',
    :tag => '1.1.0'

mod 'datacentred-ldap',
    :git => 'https://github.com/Puppet-Finland/datacentred-ldap.git'

mod 'puppetfinland-monit',
    :git => 'https://github.com/Puppet-Finland/monit.git'

mod 'puppetfinland-os',
    :git => 'https://github.com/Puppet-Finland/os.git'

mod 'puppetfinland-packetfilter',
    :git => 'https://github.com/Puppet-Finland/packetfilter.git'

mod 'puppetfinland-systemd',
    :git => 'https://github.com/Puppet-Finland/puppet-systemd.git'

mod 'puppetfinland-tomcat',
    :git => 'https://github.com/Puppet-Finland/puppet-module-tomcat.git',
    :tag => '1.1.0'
