#!/bin/sh
#
# Variables used by setup scripts. Intended to allow splitting the setup into
# smaller atomic chunks.

# Static variables
PATH=/bin:/sbin:/usr/bin:/usr/sbin
INSTANCE="vagrant"
SOURCE_DIR="/vagrant/vagrant"
PASSFILE="/tmp/pass"
PK12FILE="/tmp/keys.pk12"
PK12PASS="vagrant"
ROOTDN="cn=Directory Manager"
ROOTDN_PASS="vagrant"
NOISE="/tmp/noise"
ADMIN_DBPATH="/etc/dirsrv/admin-serv"
CONNECTION_PARAMS=""

# Sometimes not defining host and port may give misleading warnings (e.g. 
# "Invalid credentials"
CONNECTION_PARAMS="-h localhost -p 389"

# Derived variables
DBPATH="/etc/dirsrv/slapd-$INSTANCE"
PINFILE="$DBPATH/pin.txt"
ADMIN_PINFILE="$ADMIN_DBPATH/pin.txt"
NSS_CONF="$ADMIN_DBPATH/nss.conf"
